// Application.swift
// RemoteRecruit

import Foundation

// MARK: - Application Status

/// Represents the current state of a job application.
public enum ApplicationStatus: String, Codable, Equatable, Sendable, CaseIterable {
    case applied
    case inReview = "in_review"
    case shortlisted
    case rejected

    /// A human-readable label for display in the UI.
    public var displayName: String {
        switch self {
        case .applied: return "Applied"
        case .inReview: return "In Review"
        case .shortlisted: return "Shortlisted"
        case .rejected: return "Rejected"
        }
    }

    /// A short uppercase tag for compact UI elements.
    public var shortTag: String {
        switch self {
        case .applied: return "APPLIED"
        case .inReview: return "IN REVIEW"
        case .shortlisted: return "SHORTLISTED"
        case .rejected: return "REJECTED"
        }
    }

    /// SF Symbol icon for the status badge.
    public var iconName: String {
        switch self {
        case .applied: return "paperplane.fill"
        case .inReview: return "clock.fill"
        case .shortlisted: return "star.fill"
        case .rejected: return "xmark.circle.fill"
        }
    }

    /// Color name hint for SwiftUI theming.
    public var colorName: String {
        switch self {
        case .applied: return "blue"
        case .inReview: return "orange"
        case .shortlisted: return "green"
        case .rejected: return "red"
        }
    }

    /// Sorting priority (lower = higher priority in the UI).
    public var sortPriority: Int {
        switch self {
        case .shortlisted: return 0
        case .inReview: return 1
        case .applied: return 2
        case .rejected: return 3
        }
    }
}

// MARK: - Sync Status

/// Tracks the freshness of a scraped application status.
public enum SyncStatus: String, Codable, Equatable, Sendable, CaseIterable {
    case synced
    case stale
    case syncFailed = "sync_failed"
    case needsManualCheck = "needs_manual_check"

    /// A human-readable label.
    public var displayName: String {
        switch self {
        case .synced: return "Up to date"
        case .stale: return "May be outdated"
        case .syncFailed: return "Sync failed"
        case .needsManualCheck: return "Check manually"
        }
    }

    /// SF Symbol icon.
    public var iconName: String {
        switch self {
        case .synced: return "checkmark.circle.fill"
        case .stale: return "exclamationmark.circle.fill"
        case .syncFailed: return "arrow.triangle.2.circlepath"
        case .needsManualCheck: return "hand.tap.fill"
        }
    }

    /// Whether the user should be prompted to take action.
    public var requiresAction: Bool {
        switch self {
        case .synced: return false
        case .stale, .syncFailed, .needsManualCheck: return true
        }
    }
}

// MARK: - Job Application

/// Represents a user's application for a specific job listing.
public struct JobApplication: Codable, Equatable, Sendable, Identifiable, Hashable {

    // MARK: - Fields

    /// Unique document ID (auto-generated by Firestore).
    public var id: String

    /// The ID of the job listing the user applied to.
    public let jobId: String

    /// Denormalized job title for quick display without joining.
    public var jobTitle: String

    /// Denormalized company name for quick display without joining.
    public var companyName: String

    /// The Firebase Auth UID of the applicant.
    public let userId: String

    /// The download URL of the user's resume at the time of application.
    public let resumeURL: String

    /// Current review status.
    public var status: ApplicationStatus

    /// Server timestamp when the application was created.
    public let timestamp: Date

    /// When the scraper last successfully synced this application's status.
    public var lastSyncedAt: Date?

    /// The freshness status of the last sync attempt.
    public var syncStatus: SyncStatus

    /// Optional external URL for the original job listing (used for manual check).
    public var jobListingURL: String?

    /// Whether this application was submitted via Easy Apply (one-tap).
    public var isEasyApply: Bool

    /// Optional cover note added during application.
    public var coverNote: String?

    // MARK: - Init

    public init(
        id: String = UUID().uuidString,
        jobId: String,
        jobTitle: String = "",
        companyName: String = "",
        userId: String,
        resumeURL: String,
        status: ApplicationStatus = .applied,
        timestamp: Date = Date(),
        lastSyncedAt: Date? = nil,
        syncStatus: SyncStatus = .synced,
        jobListingURL: String? = nil,
        isEasyApply: Bool = false,
        coverNote: String? = nil
    ) {
        self.id = id
        self.jobId = jobId
        self.jobTitle = jobTitle
        self.companyName = companyName
        self.userId = userId
        self.resumeURL = resumeURL
        self.status = status
        self.timestamp = timestamp
        self.lastSyncedAt = lastSyncedAt
        self.syncStatus = syncStatus
        self.jobListingURL = jobListingURL
        self.isEasyApply = isEasyApply
        self.coverNote = coverNote
    }
}

// MARK: - Display Helpers

extension JobApplication {

    /// Whether the sync is stale (7+ days without an update).
    public var isStale: Bool {
        guard let lastSync = lastSyncedAt else { return true }
        return Date().timeIntervalSince(lastSync) > 7 * 24 * 60 * 60
    }

    /// Relative time string for when the application was submitted (e.g. "2 days ago").
    public var relativeAppliedDate: String {
        relativeDateString(from: timestamp)
    }

    /// Relative time string for the last sync (e.g. "3 days ago").
    public var relativeSyncDate: String {
        guard let lastSync = lastSyncedAt else { return "Never" }
        return relativeDateString(from: lastSync)
    }

    /// Company initial for avatar display.
    public var companyInitial: String {
        String(companyName.prefix(1)).uppercased()
    }

    // MARK: - Private

    private func relativeDateString(from date: Date) -> String {
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .abbreviated
        return formatter.localizedString(for: date, relativeTo: Date())
    }
}
